### ISSUE TITLE
AttributeError: module 'social_core.backends.dropbox' has no attribute 'DropboxOAuth'

### ISSUE THREAD

**Issue by miiichael** [python-social-auth/social-examples#58]
### Expected behaviour

Example runs.

### Actual behaviour

`AttributeError: module 'social_core.backends.dropbox' has no attribute 'DropboxOAuth'`

### What are the steps to reproduce this issue?

git clone https://github.com/python-social-auth/social-examples
cd social-examples/example-flask
flask --app example run
curl http://127.0.0.1:5000

### Any logs, error output, etc?

(Excuse the ruined indentation, I blame Guacamole)
```
[2024-05-23 13:37:02,652] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2525, in wsgi_app
response = self.full_dispatch_request()
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/flask/app.py", line 1822, in full_dispatch_request
rv = self.handle_user_exception(e)
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in full_dispatch_request
rv = self.dispatch_request()
  ^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/flask/app.py", line 1796, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/michael/docs/dev/social-examples/example-flask/example/routes/main.py", line 9, in main
return render_template("home.html")
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/flask/templating.py", line 147, in render_template
return _render(app, template, context)
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/flask/templating.py", line 128, in _render
  app.update_template_context(context)
File "/usr/lib/python3/dist-packages/flask/app.py", line 994, in update_template_context
context.update(func())
  ^^^^^^
  File "/mnt/home/michael/docs/dev/social-examples/example-flask/example/__init__.py", line 76, in load_common_context
return common_context(
  ^^^^^^^^^^^^^^^
  File "/mnt/home/michael/docs/dev/social-examples/example-flask/common/utils.py", line 23, in common_context
"available_backends": load_backends(authentication_backends),
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/social_core/backends/utils.py", line 34, in load_backends
backend = module_member(auth_backend)
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/social_core/utils.py", line 60, in module_member
return getattr(module, member)
^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'social_core.backends.dropbox' has no attribute 'DropboxOAuth'
```

### Any other comments?

https://dropbox.tech/developers/api-v1-deprecated suggests that DropboxOAuth has been gone more than half a decade...

**Comment by nijel** [comment]
You're right, the examples are not really maintained, help is welcome.

**Comment by miiichael** [comment]
Oh, ditto DropboxOAuth2. 😅

And GoogleOpenId, LinkedinOAuth, YahooOpenId.

**Comment by miiichael** [comment]
I may have a go at a gentle provider update PR later, at least for Flask. But I think I need to gain an understanding of the confusing bugs in my own (simple) application first. 😛
